language: java
sudo: false
dist: trusty
jdk:
- openjdk8
script:
- mvn clean package -Ddocgen.images.dir=images,documentation -Doutput.format=html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: "./target/generated-docs"
  on:
    branch: master
